2024-11-18 11:10:36,997 ERROR: 500 error:  [in C:\thread-site\vulnerability_codes\src\app.py:235]
Traceback (most recent call last):
  File "C:\thread-site\vulnerability_codes\src\app.py", line 212, in contact
    raise InternalServerError
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
